### ISSUE TITLE
Feature request: add sectors numbers to ordinary messages, and bigger separators

### ISSUE THREAD

**Issue by febs** [sellmerfud/coltwi#6]
The bot only mentions the Sectors Wilaya and number only when applying the "show all" command, or at least that was the only case where I have seen those used.

Normally the sectors are only referred to with their name.
I think that it would be very helpful to be able to _also_ see their Sector "code" alonsgide with their name, maybe even with a colored text. 
This could be optional eventually.

That's my suggestion and feature request. 
Secondarily, I would think that adding more newlines or extra --------------------------------- could help readability. Especially when the bot does loads of stuff, I find it easy to miss something along the way. 

Thank you for the bot nevertheless,

**Comment by sellmerfud** [comment]
I'll look into displaying the sector id's along with the name in the log output.

I have resisted adding colored text, because the Windows command shell does not support ANSI escape codes for color.
As far as I know there is no other way to support color on Windows.  I do not have a computer running Windows so it is not something that I can easily test.

I have thought about adding a "Press return to continue" prompt at certain points during the output of the Bot's turn so that you do not miss what is going on.  I did this with the "Fire in the Lake" program and I think it works well.

Thanks for the suggestions.

**Comment by febs** [comment]
A prompt after each step would also work very well.

Thank you,

**Comment by sellmerfud** [comment]
I just released version 2.12.
It has the improvements that you requested.
Let me know what you think.

**Comment by febs** [comment]
It is SO much better now! Thank you very much.

**Comment by febs** [comment]
I forked your project to fiddle with this and I got a result I'm pretty happy with, despite being very rough. It is working on Windows, maybe this might be of interest for you.

Here's how it looks:
![image](https://github.com/sellmerfud/coltwi/assets/604435/acb8d96c-98d5-47f2-9334-721ddd1a0510)

Regards,

**Comment by sellmerfud** [comment]
So the windows console does support color!  I didn't know.

**Comment by febs** [comment]
Well admittedly that window is the VS code terminal. I am unable to build on Windows so I am running the bot with "sbt run".

**Comment by febs** [comment]
I confirm it is also working in the ordinary dull windows terminal:

![image](https://github.com/sellmerfud/coltwi/assets/604435/506dfc55-6666-4042-b679-ae0a22a1d130)

**Comment by sellmerfud** [comment]
I added changes similar to what you did to support color.
The colors are also saved in the save files so that you get color when using the history command.

**Comment by febs** [comment]
This is amazing! Thank you!
