### ISSUE TITLE
Bot should consider potential special activities before forbidding an assault (and other ops?)

### ISSUE THREAD

**Issue by febs** [sellmerfud/coltwi#8]
I want to do a troop lift and then assault. According to the manual, special activities such as troop lift can happen _before_, during or after an operation.

> ----------------------------------------------------
> Government chooses: Execute Op & Special Activity
> 
> Choose Operation:
> ----------------------------------------------------
> 1) Train
> 2) Garrison
> 3) Sweep
> 4) Assault
> Selection: 4
> 
> There are no spaces that can be targeted by an Assault operation!

If I were allowed to do my troop lift **before** I could do a troop lift and move French troops where there are lots of active guerrillas, then assault them. At the moment though, this is forbidden.

Thanks,

**Comment by sellmerfud** [comment]
I put in the check for no valid spaces to try and be helpful to the user, but forgot that it precluded the special activity creating a valid space.  It is also done for the Sweep command.

I removed the checks so that the menu for these actions is now always displayed

If there are no valid spaces or if the user cannot afford the operation, then they will have to manually choose to abort the action.

**Comment by febs** [comment]
Yep, after opening the issue I tried again to fiddle with the code and noticed that it was sufficient to remove those "ifs".
Thanks for doing that,
